In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [111]:
pd.set_option('display.max_columns', None)

# inlezen van data

in de data zijn values in een column met verschillende Type, met low_memory=False kunt pandas bij inlezen een faste Type voor een column vast leggen.

In [112]:
df = pd.read_csv('sap_storing_data_hu_project.csv', low_memory=False)

haal alle collumn dat ? of ntv zijn

In [113]:
df = df[["stm_mon_nr","stm_vl_post","stm_sap_meld_ddt","stm_sap_meldtekst_lang","stm_sap_meldtekst","stm_geo_mld","stm_equipm_nr_mld",
                    "stm_equipm_soort_mld","stm_equipm_omschr_mld","stm_km_van_mld","stm_km_tot_mld","stm_prioriteit","stm_aanngeb_ddt","stm_oh_pg_gst",
                    "stm_geo_gst","stm_equipm_nr_gst","stm_equipm_soort_gst","stm_equipm_omschr_gst","stm_km_van_gst","stm_km_tot_gst","stm_oorz_groep",
                    "stm_oorz_code","stm_oorz_tkst","stm_fh_ddt","stm_fh_status","stm_sap_storeind_ddt","stm_tao_indicator","stm_tao_indicator_vorige",
                    "stm_tao_soort_mutatie","stm_tao_telling_mutatie","stm_tao_beinvloedbaar_indicator","stm_sap_melddatum","stm_sap_meldtijd","stm_contractgeb_mld",
                    "stm_techn_mld","stm_contractgeb_gst","stm_techn_gst","stm_aanngeb_dd","stm_aanngeb_tijd","stm_aanntpl_dd","stm_aanntpl_tijd","stm_progfh_in_datum",
                    "stm_progfh_in_tijd","stm_progfh_in_invoer_dat","stm_progfh_in_invoer_tijd","stm_progfh_in_duur","stm_progfh_gw_tijd","stm_progfh_gw_teller",
                    "stm_fh_dd","stm_fh_tijd","stm_fh_duur","stm_sap_storeinddatum","stm_sap_storeindtijd","stm_oorz_tekst_kort","stm_pplg_van","stm_pplg_naar",
                    "stm_dstrglp_van","stm_dstrglp_naar"]]

het data bastaan voraal uit drie sorten type data:<br>
tekstuele inhoud<br>
numerike classen<br>
datum en tijd<br>

In [114]:
df

,stm_mon_nr,stm_vl_post,stm_sap_meld_ddt,stm_sap_meldtekst_lang,stm_sap_meldtekst,stm_geo_mld,stm_equipm_nr_mld,stm_equipm_soort_mld,stm_equipm_omschr_mld,stm_km_van_mld,stm_km_tot_mld,stm_prioriteit,stm_aanngeb_ddt,stm_oh_pg_gst,stm_geo_gst,stm_equipm_nr_gst,stm_equipm_soort_gst,stm_equipm_omschr_gst,stm_km_van_gst,stm_km_tot_gst,stm_oorz_groep,stm_oorz_code,stm_oorz_tkst,stm_fh_ddt,stm_fh_status,stm_sap_storeind_ddt,stm_tao_indicator,stm_tao_indicator_vorige,stm_tao_soort_mutatie,stm_tao_telling_mutatie,stm_tao_beinvloedbaar_indicator,stm_sap_melddatum,stm_sap_meldtijd,stm_contractgeb_mld,stm_techn_mld,stm_contractgeb_gst,stm_techn_gst,stm_aanngeb_dd,stm_aanngeb_tijd,stm_aanntpl_dd,stm_aanntpl_tijd,stm_progfh_in_datum,stm_progfh_in_tijd,stm_progfh_in_invoer_dat,stm_progfh_in_invoer_tijd,stm_progfh_in_duur,stm_progfh_gw_tijd,stm_progfh_gw_teller,stm_fh_dd,stm_fh_tijd,stm_fh_duur,stm_sap_storeinddatum,stm_sap_storeindtijd,stm_oorz_tekst_kort,stm_pplg_van,stm_pplg_naar,stm_dstrglp_van,stm_dstrglp_naar
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,0,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,NaN,02/01/2006 09:00:00,Logboeknr Geeltje : 49 Tijd: 0900 VL-Po...,Logboeknr Geeltje : 49 Tijd: 0900,624.0,NaN,NaN,NaN,0.0,0.0,9.0,02/01/2006 09:00:00,81S,624.0,NaN,NaN,NaN,0.0,0.0,ONR-RIB,133.0,Papieren ontbreken,02/01/2006 09:00:00,4.0,02/01/2006 09:00:00,N,NaN,NaN,0,B,02/01/2006,09:00:00,NaN,NaN,81.0,S,02/01/2006,09:00:00,NaN,00:00:00,NaN,00:00:00,NaN,00:00:00,99999999.0,00:00:00,0.0,02/01/2006,09:00:00,0.0,02/01/2006,09:00:00,NaN,NaN,NaN,NaN,NaN
2,48.0,GN,02/01/2006 12:35:00,Logboeknr RBV : 48 Tijd: 1235 VL-Post: ...,Logboeknr RBV : 48 Tijd: 1235 VL-P,201.0,NaN,NaN,NaN,0.0,0.0,9.0,02/01/2006 12:35:00,37B,201.0,NaN,NaN,NaN,30200.0,0.0,ONR-DERD,143.0,NaN,02/01/2006 13:26:00,4.0,02/01/2006 13:26:00,N,NaN,NaN,0,NB,02/01/2006,12:35:00,NaN,NaN,37.0,B,02/01/2006,12:35:00,NaN,00:00:00,NaN,00:00:00,NaN,00:00:00,99999999.0,00:00:00,0.0,02/01/2006,13:26:00,51.0,02/01/2006,13:26:00,schapen op de spoorbaan!,NaN,NaN,Lp,Apg
3,72.0,ZL,02/01/2006 16:40:00,Logboeknr RBV : 72 Tijd: 1640 VL-Post: ...,Logboeknr RBV : 72 Tijd: 1640 VL-P,25.0,NaN,NaN,NaN,0.0,0.0,9.0,02/01/2006 16:40:00,32B,25.0,NaN,NaN,NaN,14000.0,0.0,ONR-DERD,142.0,NaN,02/01/2006 17:20:00,4.0,02/01/2006 17:20:00,N,NaN,NaN,0,NB,02/01/2006,16:40:00,NaN,NaN,32.0,B,02/01/2006,16:40:00,NaN,00:00:00,NaN,00:00:00,NaN,00:00:00,99999999.0,00:00:00,0.0,02/01/2006,17:20:00,40.0,02/01/2006,17:20:00,Persoon langs de baan,NaN,NaN,Hgl,NaN
4,96.0,ZL,02/01/2006 22:30:00,Logboeknr RBV : 96 Tijd: 2230 VL-Post: ...,Logboeknr RBV : 96 Tijd: 2230 VL-P,12.0,NaN,NaN,NaN,0.0,0.0,9.0,02/01/2006 22:30:00,35B,12.0,NaN,NaN,NaN,19819.0,0.0,ONR-DERD,142.0,NaN,02/01/2006 22:36:00,4.0,02/01/2006 22:36:00,N,NaN,NaN,0,NB,02/01/2006,22:30:00,NaN,NaN,35.0,B,02/01/2006,22:30:00,NaN,00:00:00,NaN,00:00:00,NaN,00:00:00,99999999.0,00:00:00,0.0,02/01/2006,22:36:00,6.0,02/01/2006,22:36:00,Bijna aanrijding met persoon,NaN,NaN,Hgv,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898521,0.0,NaN,11/05/2013 08:06:00,GVC : sp-2 en 3 stop lampen op de stootjukke...,GVC : sp-2 en 3 stop lampen op de stoot,560.0,NaN,NaN,NaN,24500.0,0.0,5.0,11/05/2013 08:06:00,02B,NaN,NaN,NaN,NaN,0.0,0.0,TECHONV,215.0,accu's waren leeg. Oorzaak: ouderdom Accu's v...,11/05/2013 09:29:00,1.0,11/05/2013 09:30:00,N,N,NaN,0,B,11/05/2013,08:06:00,NaN,NaN,2.0,B,11/05/2013,08:06:00,11/05/2013,09:05:00,11/05/2013,09:35:00,11/05/2013,09:26:18,30,00:00:00,0.0,11/05/2013,09:29:00,83.0,11/05/2013,09:30:00,NaN,NaN,NaN,NaN,11/05/2013
898522,0.0,NaN,11/05/2013 09:21:00,Whz : Ovw 100.1 albert Plesmanweg blijft dic...,Whz : Ovw 100.1 albert Plesmanweg blijft,468.0,10021085.0,OVERWEG,Havio 100.1 A Rtd Eemh. Albert Plesmanwe,100051.0,0.0,2.0,11/05/2013 09:21:00,04S,468.0,10021085.0,OVERWEG,Havio 100.1 A Rtd Eemh. Albert Plesmanwe,100051.0,0.0,TECHONV,218.0,Gestoord object: OVERWEG 100.1. Gestoordonder...,11/05/2013 10:44:00,4.0,11/05/2013 10:44:00,N,NaN,NaN,0,B,11/05/2013,09:21:00,4.0,S,4.0,S,11/05/2013,09:21:00,11/05/2013,10:08:00,11/05/2013,11:00:00,11/05/2013,10:16:27,52,00:00:00,0.0,11/05/2013,10:44:00,83.0,11/05/2013,10:44:00,NaN,NaN,NaN,NaN,NaN
898523,0.0,NaN,11/05/2013 09:21:00,Whz : Ovw 100.1 albert Plesmanweg blijft dic...,Whz : Ovw 100.1 albert Plesmanweg blijft,468.0,10021085.0,OVERWEG,Havio 100.1 A Rtd Eemh. Albert Plesmanwe,100051.0,0.0,2.0,11/05/2013 09:21:00,04S,468.0,10021085.0,OVERWEG,Havio 100.1 A Rtd Eemh. Albert Plesmanwe,100051.0,0.0,TECHONV,218.0,Gestoord object: OVERWEG 100.1. Gestoordonder...,11/05/2013 10:44:00,4.0,11/05/2013 10:44:00,N,N,NaN,0,B,11/05/2013,09:21:00,4.0,S,4.0,S,11/05/2013,09:21:00,11/05/2013,10:08:00,11/05/2013,11:00:00,11/05/2013,10:16:27,52,00:00:00,0.0,11/05/2013,10:44:00,83.0,11/05/2013,10:44:00,NaN,NaN,NaN,NaN,00/00/0000
898524,0.0,NaN,20/08/2016 14:15:17,Bdg-Apn : Km 12.7 twee gedode zwanen langs het...,Bdg-Apn : Km 12.7 twee gedode zwanen lan,102.0,NaN,NaN,NaN,0.0,0.0,2.0,20/08/2016 14:15:17,81B,102.0,NaN,NaN,NaN,0.0,0.0,ONR-RIB,135.0,Gestoord object: SPOOR LA. Gestoord onde Gesto...,20/08/2016 15:14:00,1.0,20/08/2016 15:15:00,N,NaN,NaN,0,B,20/08/2016,14:15:17,NaN,NaN,81.0,B,20/08/2016,14:15:17,20/08/2016,14:45:00,20/08/2016,16:00:00,20160820,15:16:29,75,00:00:00,0.0,20/08/2016,15:14:00,19.0,20/08/2016,15:15:00,Gestoord object: SPOOR LA. Gestoord onde,NaN,NaN,NaN,NaN
898525,0.0,NaN,20/08/2016 14:15:17,Bdg-Apn : Km 12.7 twee gedode zwanen langs het...,Bdg-Apn : Km 12.7 twee gedode zwanen lan,102.0,NaN,NaN,NaN,0.0,0.0,2.0,20/08/2016 14:15:17,81O,102.0,NaN,NaN,NaN,0.0,0.0,ONR-DERD,143.0,Gestoord object: SPOOR LA. Gestoord onde Gesto...,20/08/2016 15:14:00,1.0,20/08/2016 15:15:00,N,N,NaN,0,NB,20/08/2016,14:15:17,NaN,NaN,81.0,O,20/08/2016,14:15:17,20/08/2016,14:45:00,20/08/2016,16:00:00,20160820,15:16:29,75,00:00:00,0.0,20/08/2016,15:14:00,19.0,20/08/2016,15:15:00,Gestoord object: SPOOR LA. Gestoord onde,NaN,NaN,NaN,NaN

Tijdens de proces wanneer het model gebruik wordt zijn niet alle data zijn beschikbaar. Data dat eindig met _gst zijn niet geschikte data.

# filter doubble data

In [115]:
df = df.drop_duplicates()

# feature

In [139]:
data=df[['stm_oorz_code','stm_sap_melddatum','stm_sap_meldtijd','stm_geo_mld','stm_aanntpl_tijd','stm_fh_tijd','stm_techn_mld','stm_prioriteit','stm_contractgeb_mld','stm_fh_duur','stm_progfh_in_duur','stm_progfh_in_tijd']]

hier zijn wat feature tijdens proces beschiktbaar is en wat we intersant vinden:<br>
stm_oorz_code : code van wat de probleem is (weet pas was de aannemer aanwezig is) <br>
stm_sap_melddatum: de datum data melding melding is binnen gekommen <br>
stm_sap_meldtijd : de tijdstip van de melding <br>
stm_geo_mld: geocode waar iets gebuurt is. <br>
stm_aanntpl_tijd : de tijdmoment dat de aanmener anweizig is <br>
stm_fh_dd : de datum dat de probleem opgelost is <br>
stm_aanntpl_tijd : de tijdmoment dat de probleem opgelost is （het is binnen 8uur het kan zijn dat dit niet van belang is） <br>
stm_techn_mld: Bij welke techniekveld de melding hoort<br>
stm_prioriteit: De prioriteit zeg over hoebelangrijk en hoe snel de probleem zijn <br>
stm_fh_duur: hoelang het duurt van melding tot dat de probleem is opgelost
stm_progfh_in_tijd: tijdstip waarneer het klaar zijn.

# FHT prognose

eerts kijk we wat stm_fh_tijd presis betekend<br>
Om beter mee te rekenen zet we de tijd om in hoeveelste minuut van de dag.

In [117]:
# Kolomnamen met tijd in HH:MM:SS formaat
tijd_kolommen = ['stm_sap_meldtijd', 'stm_aanntpl_tijd', 'stm_fh_tijd','stm_progfh_in_tijd']

# Functie om tijdstring om te zetten naar totaal aantal minuten
def convert_time_to_minutes(df, columns):
    for col in columns:
        df.loc[:, col] = pd.to_datetime(df[col], format='%H:%M:%S', errors='coerce')
        df.loc[:, col] = df[col].apply(lambda x: x.hour * 60 + x.minute if pd.notnull(x) else None)
    return df

In [118]:
data = convert_time_to_minutes(data, tijd_kolommen)

In [140]:
data[['stm_sap_meldtijd', 'stm_aanntpl_tijd', 'stm_fh_tijd','stm_fh_duur']]

       stm_sap_meldtijd stm_aanntpl_tijd stm_fh_tijd  stm_fh_duur
0                   NaN              NaN         NaN          NaN
1                 540.0              0.0       540.0          0.0
2                 755.0              0.0       806.0         51.0
3                1000.0              0.0      1040.0         40.0
4                1350.0              0.0      1356.0          6.0
...                 ...              ...         ...          ...
898521            486.0            545.0       569.0         83.0
898522            561.0            608.0       644.0         83.0
898523            561.0            608.0       644.0         83.0
898524            855.0            885.0       914.0         19.0
898525            855.0            885.0       914.0         19.0

[831507 rows x 4 columns]

Hieruit blijkt dat functie hersteel duur gelijk aan hersteel tijdstip - meldings tijdstip<br>
ook zien je bij somig storing dat geen infomatie is wanneer aannemer aanweizig was.

In [141]:
len(data[data['stm_fh_duur'] == 0])

160611

In [142]:
len(data.loc[(data["stm_progfh_in_tijd"] == data["stm_fh_tijd"]) & (df["stm_fh_tijd"] != 0)])

140129

In [143]:
len(data[data['stm_fh_duur'] == (data['stm_progfh_in_tijd']-data['stm_aanntpl_tijd'])])

156596

Hieruit kunnen we zien dat 160.000 data geen stroning bij melding.<br>
140.000 data prognose functie herstel tijdstip gelijk zijn aan werkelijk hersteltijd<br>
150.00 data zijn werkelijk FHT gelijk aan tijdstip aannemer te plaats tot prognose functie herstel tijdstip

in stm_progfh_in_duur zijn str values, we bewaar eerste alle numeric waardes en zet we de type als int

In [158]:
data['stm_progfh_in_duur'] = pd.to_numeric(data['stm_progfh_in_duur'], errors='coerce')
data['stm_progfh_in_duur'] = data['stm_progfh_in_duur'].fillna(0).astype(int)

In [160]:
len(data[data['stm_progfh_in_duur'] == (data['stm_progfh_in_tijd']-data['stm_aanntpl_tijd'])])

120528

In [163]:
len(data[data['stm_progfh_in_duur'] == data['stm_fh_duur']])

8780

verder is te zien dat, 120.000 data dat prognose functie herstel tijd gelijk tijdstip aannemer te plaats + prognose functie herstel tijdstip <br>
ook zijn 9.000 data dat prognose duur gelijk aan werkelijk FHT duur

# Target

voor de traget neem we de tijd neem de functie hersteltijd van waarneer de aanmener aanweizig is tot dat weer gereiden mogen worden.<br>
we bewaar eerst alle data dat binnen dag is

In [145]:
data['targetherstel'] = np.where(
    data['stm_fh_tijd'] - data['stm_aanntpl_tijd']>= 0, # als de stm_fh_tijd-stm_aanntpl_tijd positief is
    data['stm_fh_tijd'] - data['stm_aanntpl_tijd'], # dan betekende dat nog op de zefde day is, kun je gelijk van elkaar aftrekken
    data['stm_fh_tijd'] - data['stm_aanntpl_tijd']+1440 # als niet op zelfdde dag is hersteld, dus een neagetief uitkomst moet er +1440 om de juiste tijd te krijgen.
)

C:\Users\maste\AppData\Local\Temp\ipykernel_11164\3034723497.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['targetherstel'] = np.where(

In [146]:
ranges = {
    "null": (0, 0),
    "tot 15m": (0, 15),
    "15m tot 30m": (15, 30),
    "30m tot 1h": (30, 60),
    "1h tot 2h": (60, 120),
    "2h tot 3h": (120, 180),
    "3h tot 6h": (180, 360),
    "6h tot 8h": (360, 540),
    "8h+": (540, float('inf'))
}

total = len(data)

for label, (low, high) in ranges.items():
    if label == "null":
        count = len(data[data['targetherstel'] == 0])
    else:
        count = len(data[(data['targetherstel'] > low) & (data['targetherstel'] <= high)])
    print(f'score {label}: {count/total:.2%}')

score null: 20.53%
score tot 15m: 21.31%
score 15m tot 30m: 12.51%
score 30m tot 1h: 15.28%
score 1h tot 2h: 12.22%
score 2h tot 3h: 4.81%
score 3h tot 6h: 5.22%
score 6h tot 8h: 1.74%
score 8h+: 6.38%

we zien dat dat 20% van de meldingen geen probleem zijn dat de spoor op stil staat
21% dat onder de 15 miuten is en 13% tussen 15-30 min
voor meldingen dat de spoor boven de acht uurr stil staan zij er maar 7%

# Filter

filter data's dat stm_fh_duur onder de 15 min en data's boven de 8 uur,het is niet belangrjik in deze project.<br>
we nemen data's van 15min tot 8uur, zo data de model niet telaag gaat onderschaten.

In [164]:
data = data.loc[ (data['targetherstel']>15) & (data['targetherstel']<=540)]

In [165]:
data = data.loc[ (data['stm_progfh_in_duur']>15) & (data['stm_progfh_in_duur']<=540)]

In [166]:
data = data.loc[(data["stm_progfh_in_tijd"] <= data["stm_fh_tijd"])]

In [167]:
data = data[data['stm_progfh_in_duur'] != (data['stm_progfh_in_tijd']-data['stm_aanntpl_tijd'])]

In [168]:
data = data[data['stm_progfh_in_duur'] != data['stm_fh_duur']]

In [169]:
# datum reparatie

In [170]:
data = data.copy()
#Zet de kolom om naar datetime,vervang de datum door de dag van het jaar
data.loc[:, 'stm_sap_melddatum_dag_van_het_jaar'] = pd.to_datetime(data['stm_sap_melddatum'], format='%d/%m/%Y').dt.dayofyear

# prioriteit

In [171]:
data=data.loc[(data['stm_prioriteit']!=8)&(data['stm_prioriteit']!=9)]

In [172]:
data

,stm_oorz_code,stm_sap_melddatum,stm_sap_meldtijd,stm_geo_mld,stm_aanntpl_tijd,stm_fh_tijd,stm_techn_mld,stm_prioriteit,stm_contractgeb_mld,stm_fh_duur,stm_progfh_in_duur,stm_progfh_in_tijd,targetherstel,stm_sap_melddatum_dag_van_het_jaar
140131,145.0,23/10/2014,1190.0,67.0,1414.0,46.0,S,4.0,26.0,289.0,68,42.0,72.0,296
140132,145.0,23/10/2014,1190.0,67.0,1414.0,46.0,S,4.0,26.0,289.0,68,42.0,72.0,296
140133,145.0,23/10/2014,1190.0,67.0,1414.0,46.0,S,4.0,26.0,289.0,68,42.0,72.0,296
140233,140.0,29/10/2014,1339.0,127.0,1363.0,18.0,NaN,2.0,NaN,115.0,93,16.0,95.0,302
140234,140.0,29/10/2014,1339.0,127.0,1363.0,18.0,NaN,2.0,NaN,115.0,93,16.0,95.0,302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897432,145.0,20/08/2009,1290.0,206.0,1342.0,65.0,S,2.0,32.0,210.0,163,65.0,163.0,232
897433,224.0,20/08/2009,1290.0,206.0,1341.0,65.0,S,2.0,32.0,214.0,164,65.0,164.0,232
897453,215.0,31/08/2009,31.0,502.0,985.0,50.0,NaN,5.0,NaN,1453.0,505,50.0,505.0,243
898338,218.0,02/12/2013,997.0,950.0,1320.0,192.0,NaN,5.0,NaN,634.0,312,192.0,312.0,336
898339,218.0,02/12/2013,997.0,950.0,1320.0,192.0,NaN,5.0,NaN,634.0,312,192.0,312.0,336

In [153]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import joblib
from sklearn.metrics import r2_score